notify-update: true
server:
  motd:
    enable: false
    line-1: "Minecraft Server"
    line-2: ""
spawner:
  display: "&dSpawner&f: {entity_type}"
  lore:
    - "&9Obtained by:"
    - "&fSilk Touch"
double-jump:
  # if false permission: 'essentials.event.double_jump'
  enable: false
  standing:
    multiply: 0.0
    y: 0.4
  sprinting:
    multiply: 0.4
    y: 0.4
  forward:
    multiply: 0.2
    y: 0.4
  backward:
    multiply: -0.2
    y: 0.4
  particle:
    enable: true
    type: SOUL
    offsetX: 0.3
    offsetY: 0.2
    offsetZ: 0.3
    count: 25
  sound:
    enable: true
    type: ENTITY_VEX_AMBIENT
    volume: 2.5
    pitch: 1.0
chat:
  format:
    # permission: 'essentials.event.chat.group.default'
    default: "%vault_prefix%%essentials_display_name%%vault_suffix%&f: "
    vip: "%vault_prefix%%essentials_display_name%%vault_suffix%&f: "
    staff: "%vault_prefix%%essentials_display_name%%vault_suffix%&f: "
    vanished: "&7&o&m%essentials_display_name%&f: "
    op: "%vault_prefix%&4%essentials_display_name%%vault_suffix%&f: "
  censor:
    - nigga
    - fuck
    - penis
    - porn
    - cum
    - pussy
    - vagina
    - faggot
    - gay
commands:
  rtp:
    world: world
    spread: 1250
  cooldown:
    feed: 120
    heal: 120
    repair: 3600
    rtp: 3600
  disable:
    - plugins
    - icanhasbukkit
    - version
    - about
    - me
    - stop
    - reload
connection:
  login:
    full: "Server is currently full please try again later."
    whitelisted: "Server is currently under maintenance."
  join:
    # if false permission: 'essentials.event.join.message'
    enable: true
    message: "%essentials_display_name%&e has joined the server [&a+&e]"
    sound:
      enable: true
      type: ENTITY_FOX_AMBIENT
      volume: 0.75
      pitch: 1.0
  quit:
    # if false permission: 'essentials.event.quit.message'
    enable: true
    message: "%essentials_display_name%&e has left the server [&c-&e]"
    sound:
      enable: true
      type: ENTITY_FOX_AMBIENT
      volume: 0.75
      pitch: 1.0
date:
  format: "MM-dd-yyyy"
deaths:
  # if false permission: 'essentials.event.death.location'
  send-location: true
  drop-economy:
    enable: false
    min: 1.0
    max: 5.0
  drop-player-head:
    # enable drop player heads
    enable: false
    # chance of the drop
    chance: 0.025
economy:
  enable: true
  currency: "€"
  format: "#,##0.00"
  starting-balance: 0.0
  minimum-payment: 1.00
  bank:
    enable: true
    # auto creates bank with their name first time they join
    auto-create: false
    starting-balance: 0.0
    minimum-withdraw: 1.00
    minimum-deposit: 1.00
homes:
  # if player has permission: 'essentials.command.sethome.multiple.default'
  default: 3
  vip: 6
  staff: 12
  op: 9999
levels:
  # if player has the permission 'essentials.event.level_change'
  # the player will receive particle and sound effects
  level-up:
    particle:
      enable: true
      type: SOUL
      offsetX: 0.3
      offsetY: 0.7
      offsetZ: 0.3
      count: 25
    sound:
      enable: true
      type: ENTITY_VEX_AMBIENT
      volume: 2.5
      pitch: 1.0
  level-down:
    particle:
      enable: true
      type: SOUL
      offsetX: 0.3
      offsetY: 0.7
      offsetZ: 0.3
      count: 25
    sound:
      enable: true
      type: ENTITY_VEX_AMBIENT
      volume: 2.5
      pitch: 1.0
message-of-the-day:
  welcome:
    - "&6Welcome&f %essentials_display_name%&6 to the server!"
  welcome-back:
    - "&6Welcome back&f %essentials_display_name%&6!"
    - "&6We missed you!"
  store:
    - "&6Store:"
    -  "- https://store.your-server.org"
  rules:
    - "&6Rules:"
    - "&61.&f no server crashing"
    - "&61.&f no exploits"
    - "&62.&f no griefing"
    - "&63.&f no monkieng around! uhh?"
  help:
    - "&6Help:"
    - "- https://store.your-server.org/help"
teleport:
  delay: 3
  cancel-on-move: true
  cancel-on-damage: true
crops:
  disable-tramping-farmland: true
eggs:
  disable-tramping-turtle-egg: true
  disable-tramping-sniffer-egg: true
fire:
  disable-fire-spread: true
  disable-lava-fire-spread: true
physics:
  disable-pistons: false
  disable-redstone: false
  disable-sculk: false
  disable-vault: false
projectile:
  creative:
    # instant remove on hit if creative
    instant-remove:
      arrow: true
      egg: false
      ender_pearl: false
      snowball: false
      spectral_arrow: true
      potion: false
      wind_charge: false
  removal-timer:
    # if 0 or under it is disabled
    player:
      arrow: 30
      egg: 30
      ender_pearl: 30
      snowball: 30
      spectral_arrow: 30
      potion: 30
      experience_bottle: 30
      wind_charge: 30
    snowman:
      snowball: 15
    skeleton:
      arrow: 15
    stray:
      arrow: 15
    breeze:
      breeze_wind_charge: 15
    ghast:
      fireball: 15
    ender_dragon:
      dragon_fireball: 15
    wither:
      wither_skull: 15
  cooldown:
    # if 0 or under it is disabled
    egg: 10
    snowball: 10
    bow: 5
vanish:
  # vanished can pick items if sneaking
  sneaking-picks-item: true
notification:
  # Permissions
  # essentials.event.block_break.notify
  # essentials.event.bucket_empty.notify
  # essentials.event.block_place.notify
  #
  # Placeholders
  # Player %player%, Material %material%
  # World %world%, X %x%, Y %y%, Z %z%
  enable: false
  block-break:
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
    - ANCIENT_DEBRIS
  bucket-empty:
    - LAVA_BUCKET
  block-place:
    - TNT
  message:
    - "&7---------------"
    - "&cDetected: &f%player%"
    - "&cMaterial: &f%material%"
    - "&cLocation:"
    - "&cWorld:&f %world% &cX: &f%x% &cY: &f%y% &cZ: &f%z%"
    - "&7---------------"
